[GLOBAL]
pants_version = "2.21.0"

backend_packages = [
  'pants.backend.python',
  'pants.backend.python.typecheck.mypy',
  'pants.backend.build_files.fmt.black',
]

[source]
root_patterns = [
  '/',
]

[python]
interpreter_constraints = ["==3.12.*"]
enable_resolves = true

[python.resolves]
token_store = "3rdparty/python/token_store.lock"
token_store_v2 = "3rdparty/python/token_store_v2.lock"