[GLOBAL]
pants_version = "2.21.0"

backend_packages = [
  'pants.backend.python',
  'pants.backend.python.typecheck.mypy',
  'pants.backend.build_files.fmt.black',
]

[source]
root_patterns = [
  '/',
]

[python]
interpreter_constraints = ["==3.12.*"]
