name: Pants

on: [pull_request]

jobs:
  build:
    name: Perform CI Checks
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [3.12]
    steps:
    - uses: actions/checkout@v4
    - name: Fetch base branch
      run: git fetch origin using-pants --unshallow
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - uses: pantsbuild/actions/init-pants@v8
      with:
        base-branch: using-pants
        gha-cache-key: v0
        named-caches-hash: ${{ hashFiles('token_store.lock', 'token_store_v2.lock') }}
        cache-lmdb-store: 'true'
    - name: Check BUILD files and lint
      run: |
        pants --changed-since=origin/using-pants tailor --check update-build-files --check lint
    - name: Typecheck and test changed
      run: |
        pants --changed-since=origin/using-pants --changed-dependents=transitive check test
    - name: Package changed
      run: |
        pants --changed-since=origin/using-pants --changed-dependents=transitive package
    - name: Upload pants log
      uses: actions/upload-artifact@v3
      with:
        name: pants-log
        path: .pants.d/workdir/pants.log
      if: always()  # We want the log even on failures.